import {
  loginActionTypes,
  userActionTypes,
  organizationActionTypes,
  pipelineActionTypes,
  stackActionTypes,
  stackComponentActionTypes,
  runActionTypes,
  signupActionTypes,
  forgotActionTypes,
} from '../actionTypes';

export const actionTypesHandledByRequestSaga: string[] = [
  loginActionTypes.request,
  signupActionTypes.request,
  forgotActionTypes.request,
  userActionTypes.getMyUser.request,
  userActionTypes.getUserForId.request,
  organizationActionTypes.getMyOrganization.request,
  organizationActionTypes.getInviteForCode.request,
  organizationActionTypes.getInvites.request,
  organizationActionTypes.getMembers.request,
  organizationActionTypes.invite.request,
  organizationActionTypes.deleteInvite.request,
  organizationActionTypes.retryInvoice.request,
  organizationActionTypes.invite.request,
  pipelineActionTypes.getMyPipelines.request,
  pipelineActionTypes.getPipelineForId.request,
  pipelineActionTypes.getRunsByPipelineId.request,
  stackActionTypes.getMyStacks.request,
  stackActionTypes.getStackForId.request,
  stackActionTypes.getRunsByStackId.request,
  stackComponentActionTypes.getStackComponentTypes.request,
  stackComponentActionTypes.getStackComponentList.request,
  stackComponentActionTypes.getStackComponentForId.request,
  stackComponentActionTypes.getRunsByStackComponentId.request,
  runActionTypes.getAllRuns.request,
  runActionTypes.getRunForId.request,
  runActionTypes.getGraphForRunId.request,
];
