language: "en"
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: true
  path_filters:
  - "!pnpm-lock.yaml"
  - "!dist/**"
  - "!coverage/**"
  - "!public/**"
  - "!**/*.snap"
  path_instructions:
  - path: "src/**/*.tsx"
    instructions: |
      Review React components for adherence to the ZenML design system, accessibility standards, and efficient state management.
  - path: "src/**/*.ts"
    instructions: |
      Evaluate TypeScript modules and hooks for strict typing, predictable side effects, and consistent error handling.
  - path: "src/**/*.spec.ts*"
    instructions: |
      Ensure Vitest unit tests stay deterministic, include clear assertions, and reset mocks, timers, and TanStack Query caches.
  - path: "e2e-tests/**/*.ts"
    instructions: |
      Review Playwright journeys for critical coverage, stable selectors, and lean setup/teardown flows.
  auto_review:
    enabled: false
    ignore_title_keywords:
    - "WIP"
    - "DO NOT MERGE"
    drafts: false
    base_branches:
    - "staging"
chat:
  auto_reply: true
