name: Release-pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Get the version from the github tag ref
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: latest

      - name: Build new dashboard
        run: |
          pnpm install --frozen-lockfile
          pnpm build
        env:
          VITE_API_BASE_URL: "/api/v1"
          VITE_FRONTEND_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_REO_KEY: ${{ secrets.REO_KEY }}

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@04f64206d10b4f9c882da8157ffc3dfa6ce66b3e # v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: "false"
          onlyLastTag: "true"
          stripGeneratorNotice: "true"
          issuesWoLabels: "true"
          stripHeaders: "true"

      - name: Create release archive
        run: |
          tar -zcf zenml-dashboard.tar.gz -C dist --transform="s#\.\/##" .
          sha256sum -b zenml-dashboard.tar.gz > zenml-dashboard.tar.gz.sha256

      - name: Release to GitHub
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            zenml-dashboard.tar.gz
            zenml-dashboard.tar.gz.sha256
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
